services:
  - type: web
    name: aea_kec-website
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: NODE_VERSION
        value: 20
      - key: CLIENT_URL
        value: https://aea_kec-website.onrender.com
      - key: VITE_API_URL
        value: /api
